version: '3'
services:
  app:
    build:
      context: .
    entrypoint:
    - /docker-compose-entry.sh
    ports:
    - 9000:9000
    volumes:
    - "${PWD}:/app"
    - "./docker-compose-entry.sh:/docker-compose-entry.sh"